### ISSUE TITLE
Update aircraft by ID

### ISSUE THREAD

**Issue by hwinng** [hwinng/aircraft-management-frontend#10]
Actual: status code return 304, not update
Expectaion: Return code 200 if success or 100 if failed

**Comment by Vu1911** [comment]
chỉ có thể update những aircraft đang có status Deactivated
chỉ có thể đạt đc status Deactivated lần đầu khi vừa mới tạo aircraft và gán status là Deactivated luôn

**Comment by hwinng** [comment]
closed
